-- MySQL Script generated by MySQL Workbench
-- qui 13 jun 2019 15:28:05 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `cnpj` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereço` (
  `cep` INT NOT NULL,
  `rua` VARCHAR(45) NULL DEFAULT NULL,
  `logradouro` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `dt_nascimento` DATE NULL DEFAULT NULL,
  `rg` INT NULL DEFAULT NULL,
  `telefone` INT NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vendas` (
  `nf` INT NOT NULL,
  `vendedor` VARCHAR(45) NULL DEFAULT NULL,
  `cliente` VARCHAR(45) NULL DEFAULT NULL,
  `preço_total` VARCHAR(45) NULL DEFAULT NULL,
  `data_venda` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`nf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produtos` (
  `cod_produto` INT NOT NULL,
  `preço_venda` FLOAT NOT NULL,
  `preço_custo` FLOAT NOT NULL,
  `data_compra` DATE NOT NULL,
  PRIMARY KEY (`cod_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Abastece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Abastece` (
  `lote` INT NOT NULL,
  `Fornecedor_cnpj` INT NOT NULL,
  `Produtos_cod_produto` INT NOT NULL,
  `data_entrega` DATETIME NOT NULL,
  PRIMARY KEY (`lote`),
  INDEX `fk_Fornecedor_has_Produtos_Produtos1_idx` (`Produtos_cod_produto` ASC) VISIBLE,
  INDEX `fk_Fornecedor_has_Produtos_Fornecedor_idx` (`Fornecedor_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_has_Produtos_Fornecedor`
    FOREIGN KEY (`Fornecedor_cnpj`)
    REFERENCES `mydb`.`Fornecedor` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Produtos_Produtos1`
    FOREIGN KEY (`Produtos_cod_produto`)
    REFERENCES `mydb`.`Produtos` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `cod_cliente` INT NOT NULL AUTO_INCREMENT,
  `total_pontos` INT NULL,
  `Pessoa_cpf` INT NOT NULL,
  PRIMARY KEY (`cod_cliente`),
  INDEX `fk_Cliente_Pessoa1_idx` (`Pessoa_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Pessoa1`
    FOREIGN KEY (`Pessoa_cpf`)
    REFERENCES `mydb`.`Pessoa` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fidelidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fidelidade` (
  `qte_pontos` INT NOT NULL,
  `validade` VARCHAR(45) NULL,
  `Cliente_cod_cliente` INT NOT NULL,
  INDEX `fk_Fidelidade_Cliente1_idx` (`Cliente_cod_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Fidelidade_Cliente1`
    FOREIGN KEY (`Cliente_cod_cliente`)
    REFERENCES `mydb`.`Cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `salario` INT NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `curriculo` VARCHAR(45) NOT NULL,
  `Pessoa_cpf` INT NOT NULL,
  INDEX `fk_Funcionario_Pessoa1_idx` (`Pessoa_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_Pessoa1`
    FOREIGN KEY (`Pessoa_cpf`)
    REFERENCES `mydb`.`Pessoa` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Possui`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Possui` (
  `Vendas_nf` INT NOT NULL,
  `Produtos_cod_produto` INT NOT NULL,
  `quantidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Vendas_nf`, `Produtos_cod_produto`),
  INDEX `fk_Vendas_has_Produtos_Produtos1_idx` (`Produtos_cod_produto` ASC) VISIBLE,
  INDEX `fk_Vendas_has_Produtos_Vendas1_idx` (`Vendas_nf` ASC) VISIBLE,
  CONSTRAINT `fk_Vendas_has_Produtos_Vendas1`
    FOREIGN KEY (`Vendas_nf`)
    REFERENCES `mydb`.`Vendas` (`nf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendas_has_Produtos_Produtos1`
    FOREIGN KEY (`Produtos_cod_produto`)
    REFERENCES `mydb`.`Produtos` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reside`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reside` (
  `Cliente_cod_cliente` INT NOT NULL,
  `Endereço_cep` INT NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`Endereço_cep`, `numero`),
  INDEX `fk_Cliente_has_Endereço_Endereço1_idx` (`Endereço_cep` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Endereço_Cliente1_idx` (`Cliente_cod_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_Endereço_Cliente1`
    FOREIGN KEY (`Cliente_cod_cliente`)
    REFERENCES `mydb`.`Cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Endereço_Endereço1`
    FOREIGN KEY (`Endereço_cep`)
    REFERENCES `mydb`.`Endereço` (`cep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peças`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peças` (
  `cod_peças` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `descrição` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_peças`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carros` (
  `nr_chassi` INT NOT NULL,
  `modelo` VARCHAR(45) NULL,
  `ano` INT NULL,
  `cor` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `cod_veicular` VARCHAR(45) NULL,
  PRIMARY KEY (`nr_chassi`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
